/*
 * generated by Xtext 2.32.0
 */
package it.unibo.spe.mdd.sheduler.validation;


import it.unibo.spe.mdd.sheduler.TimeUtils;
import it.unibo.spe.mdd.sheduler.services.ShedulerGrammarAccess;
import it.unibo.spe.mdd.sheduler.sheduler.*;
import it.unibo.spe.mdd.sheduler.sheduler.Date;
import it.unibo.spe.mdd.sheduler.sheduler.impl.TaskPoolSetImpl;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.validation.CheckType;

import java.time.Duration;
import java.time.LocalDateTime;
import java.time.chrono.ChronoLocalDateTime;
import java.time.temporal.ChronoField;
import java.time.temporal.ChronoUnit;
import java.util.*;

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
public class ShedulerValidator extends AbstractShedulerValidator {
    @Check(CheckType.FAST)
    public void ensureDateIsValid(Date date) {
        if (date.getYear() < 0) {
            error("Year must be positive", date, ShedulerPackage.Literals.DATE__YEAR, 0);
        }
        if (date.getMonth() < 1 || date.getMonth() > 12) {
            error("Month must be between 1 and 12", date, ShedulerPackage.Literals.DATE__MONTH, 0);
        }
        if (date.getDay() < 1 || date.getDay() > 31) {
            error("Day must be between 1 and 31", date, ShedulerPackage.Literals.DATE__DAY, 0);
        }
    }

    @Check(CheckType.FAST)
    public void ensureRelativeTimeIsValid(RelativeTime time) {
        time.getTimeSpans().forEach(v -> {
            if(v.getDuration() > ChronoUnit.FOREVER.getDuration().getNano()) {
                warning("Value of "+ v.getUnit() +" is too high", v, ShedulerPackage.Literals.CLOCK_TIME__MILLISECOND,0);
            }
            if((v.getUnit() == TimeUnit.NANOSECONDS || v.getUnit() == TimeUnit.MILLISECONDS) && (v.getDuration() < 0 || v.getDuration() > 999)) {
                error("Millisecond and nanosecond must be between 0 and 999", v.eContainingFeature(), 0);
            }
            if((v.getUnit() == TimeUnit.MINUTES || v.getUnit() == TimeUnit.SECONDS) && (v.getDuration() < 0 || v.getDuration() > 59)) {
                error("Second amd minute must be between 0 and 59", v.eContainingFeature(), 0);
            }
            if(v.getUnit() == TimeUnit.HOURS && (v.getDuration() < 0 || v.getDuration() > 24)) {
                error("Hour must be between 0 and 24", v.eContainingFeature(), 0);
            }
        });
    }

    @Check(CheckType.FAST)
    public void ensureAbsoluteTimeIsValid(AbsoluteTime time) {
        if(time.getDate().getYear() > LocalDateTime.MAX.getYear()) {
            warning("Year value is too high", time.getDate(), ShedulerPackage.Literals.DATE__YEAR, 0);
        }
        if(TimeUtils.toLocalDateTime(time).isBefore(LocalDateTime.now()) || TimeUtils.toLocalDateTime(time).isEqual(LocalDateTime.now())) {
            error("Only future dates admitted", time.getDate(), ShedulerPackage.Literals.DATE__YEAR, 0);
        }

    }

    @Check(CheckType.FAST)
    public void ensureClockTimeIsValid(ClockTime clockTime){
        if(clockTime.getHour() < 0 || clockTime.getHour() > 24){
            error("Hour must be between 0 and 24", clockTime, ShedulerPackage.Literals.CLOCK_TIME__HOUR, 0);
        }
        if(clockTime.getMinute() < 0 || clockTime.getMinute() > 59){
            error("Minute must be between 0 and 59", clockTime, ShedulerPackage.Literals.CLOCK_TIME__MINUTE, 0);
        }
        if(clockTime.getSecond() < 0 || clockTime.getSecond() > 59){
            error("Second must be between 0 and 59", clockTime, ShedulerPackage.Literals.CLOCK_TIME__SECOND, 0);
        }
        if(clockTime.getMillisecond() < 0 || clockTime.getMillisecond() > 999){
            error("Millisecond must be between 0 and 999", clockTime, ShedulerPackage.Literals.CLOCK_TIME__MILLISECOND, 0);
        }
        if(clockTime.getNanosecond() < 0 || clockTime.getNanosecond() > 999){
            error("Nanosecond must be between 0 and 999", clockTime, ShedulerPackage.Literals.CLOCK_TIME__NANOSECOND, 0);
        }
    }

    @Check(CheckType.FAST)
    public void ensureTaskNameSamePool(TaskPoolSet poolSet) {
        List<String> pools = new ArrayList<>();
        poolSet.getPools().forEach(pool -> {
             List<String> tasks = new ArrayList<>();
             pool.getTasks().forEach(task -> {
                 if ((task.getBefore() != null || task.getAfter() != null) && task.getPeriod() != null) {
                     error("Task before/after another task cannot have periodicity", task, ShedulerPackage.Literals.TASK__PERIOD, 0);
                 }
                 if(tasks.contains(task.getName())) {
                     error("Task "+ task.getName() +" already declared", task, ShedulerPackage.Literals.TASK__NAME, 0);
                 } else {
                     tasks.add(task.getName());
                 }
             });
             if(pools.contains(pool.getName())) {
                 error("Pool "+ pool.getName() +" already declared", pool, ShedulerPackage.Literals.TASK_POOL__NAME, 0);
             } else {
                 pools.add(pool.getName());
             }
        });

    }
}
